// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrBWGvCH4UvMbZU7JRP570J-JVDdrSIdE',
    appId: '1:164071760517:web:8d867d3a109305818e7fec',
    messagingSenderId: '164071760517',
    projectId: 'test-firebase-project-44021',
    authDomain: 'test-firebase-project-44021.firebaseapp.com',
    storageBucket: 'test-firebase-project-44021.firebasestorage.app',
    measurementId: 'G-FTH7CWWXR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdvjWz_QQgUV3tCoNQ-aponJsfwswfhLo',
    appId: '1:164071760517:android:16c525e951854a9d8e7fec',
    messagingSenderId: '164071760517',
    projectId: 'test-firebase-project-44021',
    storageBucket: 'test-firebase-project-44021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU4zRJkH0DbmyZ6J5AVwp1DdqUj6YzKRI',
    appId: '1:164071760517:ios:201889145495f80a8e7fec',
    messagingSenderId: '164071760517',
    projectId: 'test-firebase-project-44021',
    storageBucket: 'test-firebase-project-44021.firebasestorage.app',
    iosBundleId: 'com.example.testFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU4zRJkH0DbmyZ6J5AVwp1DdqUj6YzKRI',
    appId: '1:164071760517:ios:201889145495f80a8e7fec',
    messagingSenderId: '164071760517',
    projectId: 'test-firebase-project-44021',
    storageBucket: 'test-firebase-project-44021.firebasestorage.app',
    iosBundleId: 'com.example.testFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrBWGvCH4UvMbZU7JRP570J-JVDdrSIdE',
    appId: '1:164071760517:web:c067ba166b80c0cf8e7fec',
    messagingSenderId: '164071760517',
    projectId: 'test-firebase-project-44021',
    authDomain: 'test-firebase-project-44021.firebaseapp.com',
    storageBucket: 'test-firebase-project-44021.firebasestorage.app',
    measurementId: 'G-8CDGYR3QDV',
  );
}
